export default {
   preset: 'ts-jest',
   testEnvironment: 'jsdom',
   transform: {
      '^.+\\.tsx?$': 'ts-jest',
   },
   moduleNameMapper: {
      '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
      '^.+\\.svg$': 'jest-transformer-svg',
      '^@/(.*)$': '<rootDir>/src/$1',
      '^@Assets/(.*)$': '<rootDir>/src/Assets/$1',
      '^@Components/(.*)$': '<rootDir>/src/Components/$1',
      '^@Data/(.*)$': '<rootDir>/src/Data/$1',
      '^@Layouts/(.*)$': '<rootDir>/src/Layouts/$1',
      '^@Configs/(.*)$': '<rootDir>/src/Libs/Configs/$1',
      '^@Handlers/(.*)$': '<rootDir>/src/Libs/Handlers/$1',
      '^@Hooks/(.*)$': '<rootDir>/src/Libs/Hooks/$1',
      '^@Providers/(.*)$': '<rootDir>/src/Libs/Providers/$1',
      '^@Schemas/(.*)$': '<rootDir>/src/Libs/Schemas/$1',
      '^@Themes/(.*)$': '<rootDir>/src/Libs/Themes/$1',
      '^@Typings/(.*)$': '<rootDir>/src/Libs/Typings/$1',
      '^@Utils/(.*)$': '<rootDir>/src/Libs/Utils/$1',
      '^@Validations/(.*)$': '<rootDir>/src/Libs/Validations/$1',
      '^@Pages/(.*)$': '<rootDir>/src/Pages/$1',
      '^@Queries/(.*)$': '<rootDir>/src/Queries/$1',
      '^@Services/(.*)$': '<rootDir>/src/Services/$1',
      '^@Styles/(.*)$': '<rootDir>/src/Styles/$1',
   },
   setupFilesAfterEnv: ['./jest.setup.ts'],
};
