export default {
   preset: 'ts-jest',
   testEnvironment: 'jsdom',
   transform: {
      '^.+\\.tsx?$': 'ts-jest',
   },
   moduleNameMapper: {
      '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
      '^.+\\.svg$': 'jest-transformer-svg',
      '^@/(.*)$': '<rootDir>/src/$1',
      '^@assets/(.*)$': '<rootDir>/src/assets/$1',
      '^@components/(.*)$': '<rootDir>/src/components/$1',
      '^@data/(.*)$': '<rootDir>/src/data/$1',
      '^@layouts/(.*)$': '<rootDir>/src/layouts/$1',
      '^@configs/(.*)$': '<rootDir>/src/libs/configs/$1',
      '^@handlers/(.*)$': '<rootDir>/src/libs/handlers/$1',
      '^@hooks/(.*)$': '<rootDir>/src/libs/hooks/$1',
      '^@providers/(.*)$': '<rootDir>/src/libs/providers/$1',
      '^@schemas/(.*)$': '<rootDir>/src/libs/schemas/$1',
      '^@themes/(.*)$': '<rootDir>/src/libs/themes/$1',
      '^@typings/(.*)$': '<rootDir>/src/libs/typings/$1',
      '^@utils/(.*)$': '<rootDir>/src/libs/utils/$1',
      '^@validations/(.*)$': '<rootDir>/src/libs/validations/$1',
      '^@pages/(.*)$': '<rootDir>/src/pages/$1',
      '^@queries/(.*)$': '<rootDir>/src/queries/$1',
      '^@services/(.*)$': '<rootDir>/src/services/$1',
      '^@styles/(.*)$': '<rootDir>/src/styles/$1',
   },
   setupFilesAfterEnv: ['./jest.setup.ts'],
};
