import {AxiosResponse} from "axios";

export type getAssetsResponse = {
    data: AxiosResponse | null;
    error: any;
}

export type getAssetResponse = {
    data: AxiosResponse | null;
    error: any;
}

export type getAssetHistoryResponse = {
    data: AxiosResponse | null;
    error: any;
}
export type AssetName =
    'bitcoin'
    | 'ethereum'
    | 'tether'
    | 'bnb'
    | 'solana'
    | 'usdc'
    | 'dogecoin'
    | 'xrp'
    | 'cardano'
    | 'shiba inu'
    | 'avalanche'
    | 'wrapped bitcoin'
    | 'polkadot'
    | 'chainlink'
    | 'tron'
    | 'bitcoin cash'
    | 'near protocol'
    | 'polygon'
    | 'uniswap'
    | 'litecoin'
    | 'internet computer'
    | 'unus sed leo'
    | 'multi collateral dai'
    | 'ethereum classic'
    | 'render token'
    | 'filecoin'
    | 'stellar'
    | 'crypto.com coin'
    | 'the graph'
    | 'okb'
    | 'stacks'
    | 'maker'
    | 'monero'
    | 'arweave'
    | 'vechain'
    | 'lido dao'
    | 'theta'
    | 'fantom'
    | 'thorchain'
    | 'cosmos'
    | 'fetch.ai'
    | 'injective'
    | 'aave'
    | 'hedera hashgraph'
    | 'algorand'
    | 'flow'
    | 'gala'
    | 'bitcoin sv'
    | 'akash network'
    | 'singularitynet'
    | 'chiliz'
    | 'axie infinity'
    | 'quant'
    | 'neo'
    | 'pendle'
    | 'the sandbox'
    | 'kucoin token'
    | 'gnosis'
    | 'ecash'
    | 'tezos'
    | 'multiversx'
    | 'eos'
    | 'mina'
    | 'aioz network'
    | 'conflux'
    | 'decentraland'
    | 'nexo'
    | 'pancakeswap'
    | 'iota'
    | 'livepeer'
    | 'kava'
    | 'gatetoken'
    | 'nervos network'
    | 'dexe'
    | 'theta fuel'
    | 'synthetix'
    | 'klaytn'
    | 'helium'
    | 'woo'
    | 'curve dao token'
    | 'oasis'
    | 'nxm'
    | 'ocean protocol'
    | 'ftx token'
    | 'golem'
    | 'compound'
    | 'wemix'
    | 'trueusd'
    | 'xinfin network'
    | 'enjin coin'
    | '1inch network'
    | 'iotex'
    | 'superverse'
    | 'skale'
    | 'celo'
    | 'rocket pool'
    | '0x protocol'
    | 'raydium'
    | 'trust wallet token'
    | 'ankr'